source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/D-Monarch/wyspecs.git'
use_frameworks!

platform :ios, '8.0'

target 'WYRouter_Example' do
  pod 'WYRouter', :path => '../'

  target 'WYRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
